using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Server.Model
{
    /// <summary>
    /// An object that represents the clients connected to the server
    /// </summary>
    class Client
    {
        //parameters

        /// <summary>
        /// The ID of the client, generated by server
        /// </summary>
        private double clientID;


        //methods

        /// <summary>
        /// default constructor
        /// </summary>
        public Client()
        {

        }//Client

        /// <summary>
        /// constructor that sets the clientID
        /// </summary>
        /// <param name="ID">the identifying ID</param>
        public Client(double ID)
        {
            clientID = ID;
        }//Client
        
        /// <summary>
        /// getter for ClientID
        /// </summary>
        /// <returns>the clientID as a double</returns>
        public double getID()
        {
            return clientID;
        }//getID

        /// <summary>
        /// setter for ClientID
        /// </summary>
        /// <param name="id">whatever the ID should be</param>
        public void setID(double id)
        {
            clientID = id;
        }//setID

        

    }
}
